version: '3.8'

services:
  flask:
    build:
      context: ./flask
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  nextjs:
    build:
      context: ./nextjs
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://flask:8080/api
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
