version: '3.8'

services:
  flask:
    build:
      context: ./flask
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.prod
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://flask:8080/api
    depends_on:
      - flask
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 512m

networks:
  app-network:
    driver: bridge
